CREATE DATABASE IF NOT EXISTS clinica_veterinaria;USE clinica_veterinaria;
CREATE TABLE IF NOT EXISTS usuarios(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(100) NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,senha VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS animais(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(100) NOT NULL,especie VARCHAR(80) NOT NULL,idade INT NOT NULL,nome_dono VARCHAR(150) NOT NULL);
CREATE TABLE IF NOT EXISTS veterinarios(id INT AUTO_INCREMENT PRIMARY KEY,nome VARCHAR(150) NOT NULL,especialidade VARCHAR(100) NOT NULL,telefone VARCHAR(30) NOT NULL);
CREATE TABLE IF NOT EXISTS consultas(id INT AUTO_INCREMENT PRIMARY KEY,animal VARCHAR(100) NOT NULL,veterinario VARCHAR(150) NOT NULL,data DATE NOT NULL,horario TIME NOT NULL);